# Telegram
telegram.bot.token=8071429817:AAHOMmPil4QZUEgD54wrb8cgSBlnmitAxb8
telegram.bot.username=Metta-Bot

# Spring
spring.application.name=Metta-Bot
logging.level.root=INFO

# H2
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:file:~/mettaDb;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE
spring.datasource.username=alex
spring.datasource.password=wowPass2!w00r?ddd
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect